# Generated by Django 4.2.13 on 2024-06-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='blocker',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='blocked',
            new_name='to_user',
        ),
    ]
