# Generated by Django 4.2.13 on 2024-05-27 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_player_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
    ]
