# Generated by Django 4.1.13 on 2024-08-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_message_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='active_shifumi_game',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
