# Generated by Django 4.2.13 on 2024-06-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_blocker_block_from_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='timestamp',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='friendrequest',
            old_name='timestamp',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
