# Generated by Django 4.1.13 on 2024-07-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_timestamp_block_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='OnlineStatus',
            field=models.BooleanField(default=False),
        ),
    ]
