# Generated by Django 4.1.13 on 2024-07-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_timestamp_block_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='activation_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
