# Generated by Django 4.1.13 on 2024-08-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_player_active_shifumi_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_game_invite',
            field=models.BooleanField(default=False),
        ),
    ]
