# Generated by Django 4.1.13 on 2024-09-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_message_is_game_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='in_pong_game',
            field=models.BooleanField(default=False),
        ),
    ]
