# Generated by Django 4.2.13 on 2024-05-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_player_options_alter_player_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
