# Generated by Django 4.1.13 on 2024-09-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_player_in_pong_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineStatus',
        ),
    ]
