# Generated by Django 4.1.13 on 2024-09-29 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_onlinestatus'),
        ('users', '0006_game_type'),
    ]

    operations = [
    ]
