# Generated by Django 4.1.13 on 2024-10-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_0006_delete_onlinestatus_0006_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
