# Generated by Django 4.1.13 on 2024-08-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmaking',
            name='room_name',
            field=models.CharField(default='', max_length=70),
        ),
    ]
