# Generated by Django 4.1.13 on 2024-09-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_game', '0003_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='final_position',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
