# Generated by Django 4.1.13 on 2024-09-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_game', '0004_tournament_final_position_tournament_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='players',
        ),
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.JSONField(default=list),
        ),
    ]
