# Generated by Django 4.1.13 on 2024-10-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_game', '0005_remove_tournament_players_tournament_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmaking',
            name='game_type',
            field=models.CharField(choices=[('pong', 'Pong'), ('shifumi', 'Shifumi')], default='pong', max_length=20),
        ),
    ]
